# Generated by Django 4.0.6 on 2022-07-07 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.ForeignKey(help_text="Choose restaurant's location", null=True, on_delete=django.db.models.deletion.CASCADE, to='noon.location'),
        ),
    ]
