# Generated by Django 4.0.6 on 2022-07-07 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noon', '0002_remove_restaurant_address_restaurant_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='description',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lunch_hours',
            field=models.CharField(default='11am - 3pm', help_text='Lunch serving hours', max_length=200, verbose_name='Lunch hours'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_location',
            field=models.ForeignKey(help_text="Choose restaurant's location", null=True, on_delete=django.db.models.deletion.CASCADE, to='noon.location'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Street address'),
        ),
    ]
