# Generated by Django 4.0.6 on 2022-07-07 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noon', '0003_remove_restaurant_description_restaurant_lunch_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmenu',
            name='dish',
            field=models.OneToOneField(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='noon.restaurant'),
        ),
    ]
