# Generated by Django 4.0.6 on 2022-07-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noon', '0004_alter_restaurantmenu_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantmenu',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurantmenu',
            name='dish',
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='dish',
            field=models.ManyToManyField(max_length=200, related_name='restaurant', to='noon.restaurant'),
        ),
    ]
