# Generated by Django 4.0.6 on 2022-07-07 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noon', '0006_alter_restaurantmenu_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmenu',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='noon.restaurant', verbose_name='Restaurant'),
        ),
    ]
