# Generated by Django 4.0.6 on 2022-07-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noon', '0007_restaurantmenu_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantmenu',
            name='dish',
        ),
    ]
