# Generated by Django 4.0.6 on 2022-07-09 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noon', '0010_remove_restaurantmenu_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantmenu',
            name='dish',
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='dessert',
            field=models.CharField(default='name of the dish', max_length=200, null=True, verbose_name='Dessert'),
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='main',
            field=models.CharField(default='name of the dish', max_length=200, verbose_name='Main'),
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='noon.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='soup',
            field=models.CharField(default='name of the dish', max_length=200, verbose_name='Soup'),
        ),
    ]
