# Generated by Django 4.0.6 on 2022-07-09 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noon', '0013_alter_restaurantweeklymenu_dessert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_location',
            field=models.ForeignKey(help_text="Choose restaurant's location", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='noon.location'),
        ),
    ]
