# Generated by Django 4.0.6 on 2022-07-16 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noon', '0014_alter_restaurant_restaurant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='today',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='week', to='noon.restaurantweeklymenu', verbose_name='Week'),
        ),
    ]
