# Generated by Django 4.0.6 on 2022-07-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noon', '0015_restaurant_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='today',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='today', to='noon.restaurantweeklymenu', verbose_name='Week'),
        ),
    ]
