# Generated by Django 4.0.6 on 2022-07-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noon', '0017_restaurant_reader_restaurantweeklymenu_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='reader',
        ),
    ]
