# Generated by Django 4.0.6 on 2022-07-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noon', '0019_restaurant_favourites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='today',
        ),
    ]
